
create database MYDB;
CREATE TABLE CUSTOMERS(
CUST_ID int NOT null auto_increment,
CUST_FRISTNAME varchar(200) NOT NULL,
CUST_LASTNAME varchar(200) NOT NULL,
CUST_NICKNAME varchar(200) NOT NULL,
CUST_AGE int,
CUST_GENDER varchar(200) NOT NULL,
CUST_COUNTRY varchar(200) NOT NULL,
CUST_SALARY decimal NOT NULL,
primary key (CUST_ID)

); 
INsert into customers(CUST_ID, CUST_FRISTNAME,CUST_LASTNAME,CUST_GENDER,CUST_COUNTRY,CUST_SALARY)
value(1,"NICK","JONES","MALE","USA",20000000),
(222,"MARITAL","MALE","FRANCE",10000000),
(333,"ROSS","GELLER","MALE","UZBEKISTAN",36000000),
(444,"CHANDLER","BING","MALE","UNKNOWN",34000000),
(555,"RACHEL","GREEN", "FEMELE", "KAZAKHSTAN", 400000),
(666, "NICK", "JONES", "MALE", "USA", 20000000),
(777, "POUL", "POGBA", "MALE", "FRANCE", 20000000),
(888,"JOYE", "TRIBBIANI", "MALE" "ETHIOPIA", 70000000);

-- UPDATE CUST_ID =333 , 444, 555
-- DELETE CUST_NAME=NICK JONES
-- WHICH CUST_ID IS 666



-- DROP TABLE customers;
-- ALTER TABLE customers
-- ADD BONUS int NOT NULL,
-- MODIFY CUST_AGE INT NOT null,
-- ALTER TABLE customers
-- DROP CUST_NICKNAME;
-- ALTER TABLE customers
-- DROP BONUS;
-- ALTER table customers RENAME TO CUSTOMER 
-- DROP TABLE customer
-- DROP database mydb
-- CREATE DATABASE MYDB
-- DROP TABLE customers
-- ALTER TABLE customers
-- DROP column CUST_BONUS;

-- SELECT * FROM mydb.address;
 SELECT * FROM mydb.customers;
update customers
SET CUST_COUNTRY  = "ETHIOPIA"
WHERE CUST_ID = 333 or CUST_ID =444 or CUST_ID =  555;

DELETE FROM CUSTOMERS
WHERE CUST_ID = 666

-- CREATING TABLE NAMING ADDRESS
create table address(
CUST_ZIP varchar(50) NOT NULL,
CUST_STREET VARCHAR (50) NOT NULL,
CUST_CITY VARCHAR (50) NOT NULL,
CUST_STATE VARCHAR (50),
CUST_ID INT,
PRIMARY KEY (CUST_ZIP),
FOREIGN KEY (CUST_ID) references CUSTOMERS (CUST_ID)
);

INSERT INTO ADDRESS (CUST_ZIP, CUST_STREET, CUST_CITY, CUST_STATE, CUST_ID)
VALUE(1000,"MEGENAGNA","ADDIS ABABA", "ADDIS ABABA", 444),
(2000, "4-KILO","ADDIS ABABA","ADDIS ABABA", 555),
(3000, "41-EYESUS","ADDIS ABABA", "ADDIS ABABA",777),
(4000, "6-KILO","ADDIS ABABA", "ADDIS ABABA",333);
INSERT INTO ADDRESS (CUST_ZIP, CUST_STREET, CUST_CITY, CUST_STATE, CUST_ID)
VALUE (5000,"01-ST","ADELANTO","CALIFORNIA",null),
(6000,"KU-ROAD","LOS ANGELES","CALIFORNIA",null),
(7000, "JK ROAD","MIAMIL","FLORIDA",null);



